create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null default '',
  approved boolean not null default false,
  role text not null default 'user',
  created_at timestamptz not null default now(),

  constraint profiles_role_check check (role in ('user', 'admin'))
);

create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  title text not null,
  movie text not null default '',
  singer text not null default '',
  original_key text not null default '',
  chord text not null default '',
  lyrics text not null,
  title_norm text not null,
  movie_norm text not null default '',
  singer_norm text not null default '',
  created_by uuid references public.profiles(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint songs_title_not_empty check (length(trim(title)) > 0),
  constraint songs_lyrics_not_empty check (length(trim(lyrics)) > 0),
  constraint songs_title_norm_unique unique (title_norm)
);

create table if not exists public.bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  created_at timestamptz not null default now(),

  constraint bookmarks_user_song_unique unique (user_id, song_id)
);

create table if not exists public.live_song_events (
  id bigint generated by default as identity primary key,
  song_id bigint not null references public.songs(id) on delete cascade,
  shared_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists songs_title_idx on public.songs (title);
create index if not exists songs_title_norm_idx on public.songs (title_norm);
create index if not exists songs_movie_norm_idx on public.songs (movie_norm);
create index if not exists songs_singer_norm_idx on public.songs (singer_norm);
create index if not exists bookmarks_user_id_idx on public.bookmarks (user_id);
create index if not exists bookmarks_song_id_idx on public.bookmarks (song_id);
create index if not exists live_song_events_created_at_idx on public.live_song_events (created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists songs_set_updated_at on public.songs;

create trigger songs_set_updated_at
before update on public.songs
for each row
execute function public.set_updated_at();

create or replace function public.is_approved()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and approved = true
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and approved = true
      and role = 'admin'
  );
$$;

alter table public.profiles enable row level security;
alter table public.songs enable row level security;
alter table public.bookmarks enable row level security;
alter table public.live_song_events enable row level security;

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles
for select
to authenticated
using (
  id = auth.uid()
  or public.is_admin()
);

drop policy if exists "songs_select_approved" on public.songs;
create policy "songs_select_approved"
on public.songs
for select
to authenticated
using (public.is_approved());

drop policy if exists "songs_insert_approved" on public.songs;
create policy "songs_insert_approved"
on public.songs
for insert
to authenticated
with check (public.is_approved());

drop policy if exists "songs_update_approved" on public.songs;
create policy "songs_update_approved"
on public.songs
for update
to authenticated
using (public.is_approved())
with check (public.is_approved());

drop policy if exists "songs_delete_approved" on public.songs;
create policy "songs_delete_approved"
on public.songs
for delete
to authenticated
using (public.is_approved());

drop policy if exists "bookmarks_select_own" on public.bookmarks;
create policy "bookmarks_select_own"
on public.bookmarks
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "bookmarks_insert_own" on public.bookmarks;
create policy "bookmarks_insert_own"
on public.bookmarks
for insert
to authenticated
with check (
  user_id = auth.uid()
  and public.is_approved()
);

drop policy if exists "bookmarks_delete_own" on public.bookmarks;
create policy "bookmarks_delete_own"
on public.bookmarks
for delete
to authenticated
using (user_id = auth.uid());

drop policy if exists "live_song_events_select_approved" on public.live_song_events;
create policy "live_song_events_select_approved"
on public.live_song_events
for select
to authenticated
using (public.is_approved());

drop policy if exists "live_song_events_insert_approved" on public.live_song_events;
create policy "live_song_events_insert_approved"
on public.live_song_events
for insert
to authenticated
with check (
  shared_by = auth.uid()
  and public.is_approved()
);
